### ISSUE TITLE
[Dashboard]: Create dashboard page with columns for each status

### ISSUE THREAD

**Issue by ndnrlg** [CMU-313/fall22-hw3-commit-tea#1]
Dashboard will sort applicants (summary-boxes) using the GPA range into a column in the status field.

Core functionality - we set this to core functionality because without a skeleton for the dashboard webpage, there is no dashboard.
**Estimated effort**: 2 days - In addition to creating the website skeleton with different columns for each status, it'll take a good amount of time to allow the webpage to resize dynamically and test that the UI behavior is correct. In addition, we will need to link to this page from the Teedy homepage.
**Dependencies**:  GPA field #7 and #10  , Status field #8 
**Acceptance criteria**: Column's include status fields and accepts/uses summary box object

**Comment by nptitanium24** [comment]
Resolved by #16
