### ISSUE TITLE
[Dashboard]: Build a summary box object used for applicants 

### ISSUE THREAD

**Issue by nicole-xiang** [CMU-313/fall22-hw3-commit-tea#3]
[Core functionality for the first sprint]
Build a summary box object that represents applicant information including the name, statistics like GPA, and action buttons like change status and edit. 
We set this to core functionality because this is a key part of our dashboard.
**Estimated effort**: 1 Day; Need to figure out how to represent data with object class 
**Dependencies**: dashboard with columns based on status #1 
**Acceptance criteria**: object represents actual content accurately including GPA, current status, and student information.

**Comment by pranavaddepalli** [comment]
Redundant issue
