### ISSUE TITLE
[Dashboard]: Sort summary boxes by GPA range in columns

### ISSUE THREAD

**Issue by ndnrlg** [CMU-313/fall22-hw3-commit-tea#4]
Using the dashboard page and summary box objects to sort applicants into the dashboard columns.
secondary functionality
We set this to secondary functionality because even if sorting isn't implemented, we can still make use of the GPA field by printing out the applicant's GPAs.
Estimated effort: 1 day. Need to update the API to return documents in sorted order
Dependencies: Dashboard page #1, summary boxes (#2 #3)
Acceptance criteria: Correctly sorts applicants (given input GPA's) into respective status column in dashboard page

**Comment by pranavaddepalli** [comment]
Not necessary
