### ISSUE TITLE
[Dashboard]: New applicant button

### ISSUE THREAD

**Issue by nptitanium24** [CMU-313/fall22-hw3-commit-tea#6]
[Secondary Functionality]
On the dashboard page we will have a button that allows users to create a new applicant by redirecting the user to the existing new document page. 
 We set this to secondary functionality because even without this feature, the dashboard could still be useful.
**Estimated effort**:  2 hours. Need to learn how to use Angular components, create the button, add actions, then test.
**Dependencies**: Requires dashboard page with columns for each status (#1)
**Acceptance criteria**: New applicant button redirects to page for creating a new document when pressed.

**Comment by nicole-xiang** [comment]
Added new applicant button to dashboard page that links to add document page. 

<img width="1349" alt="Screen Shot 2022-10-05 at 10 52 50 PM" src="https://user-images.githubusercontent.com/68407782/194203433-da9de58b-37c3-4bf5-9aa5-762cad816d32.png">
