### ISSUE TITLE
[GPA]: Add GPA field to New/Edit Document form

### ISSUE THREAD

**Issue by ndnrlg** [CMU-313/fall22-hw3-commit-tea#7]
The GPA buttons will need to be added to the document form (frontend) and fully updated in the document model (backend).

Core functionality - we set this to core functionality because without the GPA field, we won't be able to filter and search based on GPA in our dashboard, which we thought was a key feature in our dashboard.
**Estimated effort**:  6 hours - This will encompass adding a field to the HTML of the new document form, along with a post request to update the GPA in the backend.
**Dependencies**: None
**Acceptance criteria**: The GPA buttons should include ranges, in which you are only able to select one option/range, and this frontend should be connected (through middleware) to backend database with GPA field.

**Comment by nptitanium24** [comment]
Fixed by #14
